version: '3'
services:
    db:
        image: mysql:5.7
        container_name: mysql.erpsystem.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        ports:
            - 127.0.0.1:${DATABASE_PORT}:3306
        volumes:
            - ~/data/mysql.erpsystem.docker:/var/lib/mysql

    db_test:
        image: mysql:5.7
        container_name: mysql_test.erpsystem.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${TEST_DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        ports:
            - 127.0.0.1:${TEST_DATABASE_PORT}:3306
        volumes:
            - ~/data/mysql_test.erpsystem.docker:/var/lib/mysql
